### PR TITLE
Update Streamlit with new experimental feature (ENABLE_STREAMLIT_VERSIONED_STAGE)

### PR DESCRIPTION
**Pull request by sfc-gh-wschmitt**
### Pre-review checklist
   * [x] I've confirmed that instructions included in README.md are still correct after my changes in the codebase.
   * [x] I've added or updated automated unit tests to verify correctness of my new code.
   * [ ] I've added or updated integration tests to verify correctness of my new code.
   * [x] I've confirmed that my changes are working by executing CLI's commands manually on MacOS.
   * [ ] I've confirmed that my changes are working by executing CLI's commands manually on Windows.
   * [x] I've confirmed that my changes are up-to-date with the target branch.
   * [x] I've described my changes in the release notes.
   * [x] I've described my changes in the section below.

### Changes description

The Streamlit in Snowflake team is working on revamping the embedded stage experience. Effectively, we will be sunsetting Checkouts 0.5 Streamlit apps (eg. apps created in accounts where ENABLE_STREAMLIT_EMBEDDED_STAGE=true) and replacing them with Versioned Stages.

Long-term, we will be removing ENABLE_STREAMLIT_EMBEDDED_STAGE functionality altogether and replacing it entirely with versioned_stages.

The changes here will mirror the existing functionality for _Notebooks_, but gated behind several flags.
* `alter streamlit … COMMIT` becomes `alter streamlit … add live version from last`
* In some deployments, embedded_stage is sunsetting, so `COMMIT` will no longer work altogether.
* When using versioned_stages, stage path goes from `snow://streamlit/$FQN/` to `snow://streamlit/$FQN/versions/$VERSION_ALIAS`

you can test these changes by using `--experimental` and updating your config.toml
```toml
[cli.features]
enable_streamlit_no_checkouts = true 
enable_sreamlit_versioned_stage = true # use false for existing checkouts0.5 apps
```

### Release Notes

Refactored streamlit experimental deploy with upcoming git support.

### CODE REVIEW

**Review by sfc-gh-cgorrie — APPROVED** [review]
Changes in `tests/project/test_config.py` look good from NADE's POV and are consistent with the rest of the PR

**Review by sfc-gh-turbaszek — APPROVED** [review]

**Review by sfc-gh-astus — APPROVED** [review]

**Pull request merged**
